apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: us3p71xom-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/us3p71xom-java-quarkus-gitops